name: "Pull Request"

on:
  pull_request:

jobs:
  checks:
    name: "Run checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Install JDK"
        uses: actions/setup-java@v1.4.1
        with:
          java-version: 8

      - name: "Checkout the source code"
        uses: actions/checkout@v2.3.2

      - name: "Assemble"
        run: ./gradlew assembleDebug assembleRelease
